###
# 등록된 포스트 글의 목록을 가져옴
# QUERY STRING
# - page {number}: 페이지, 기본값 1
# - limit {number}: 한 페이지에 보일 문서의 수
# - q {string}: 검색 쿼리, 형식은 <검색할 필드 목록>=<키워드>
#   * <검색할 필드 목록>: 필드의 목록을 공백없이 콤마(,)로 구분하여 나열, 가능한 필드: title
GET http://localhost:5001/v1/posts?limit=10&page=1


###
# 로그인을 하지 않고 글 작성하기
POST http://localhost:5001/v1/posts
Content-Type: application/json

{
  "title": "글제목",
  "content": "로그인 하기 전 글을 작성하면 오류입니다."
}

###
# 글을 작성하기 전 로그인 필요
# 인증 서버를 통해 로그인
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "1234"
}


###
# 로그인 이후 글 작성
POSt http://localhost:5001/v1/posts
Content-Type: application/json
x-access-token: <로그인해서 발급 받은 access token 입력>

{
  "title": "글제목",
  "content": "로그인 후 글을 작성."
}

###
# PARAMS: /v1/posts/<id>
# - <id> {string}: 문서의 아이디(_id)
# 작성된 글 가져오기
GET http://localhost:5001/v1/posts/602dd907c9feb347bc5c3aa0


###
# PARAMS: /v1/posts/<id>
# - <id> {string}: 문서의 아이디(_id)
# 로그인 하지 않고 글 수정하기
PUT http://localhost:5001/v1/posts/602dd907c9feb347bc5c3aa0
Content-Type: application/json

{
  "content": "로그인 하지 않은 사람은 글을 수정할 수 없습니다."
}


###
# 관리자 로그인(다른 사람 로그인)
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "admin@domain.com",
  "password": "asdf1234"
}

###
# PARAMS: /v1/posts/<id>
# - <id> {string}: 문서의 아이디(_id)
# 다른 사람의 글 수정
PUT http://localhost:5001/v1/posts/602dd907c9feb347bc5c3aa0
Content-Type: application/json
x-access-token: <다른 사용자의 access token 입력>

{
  "content": "본인이 작성하지 않은 글은 수정할 수 없습니다."
}

###
# PARAMS: /v1/posts/<id>
# - <id> {string}: 문서의 아이디(_id)
# 수정된 글 확인
GET http://localhost:5001/v1/posts/602dd907c9feb347bc5c3aa0


###
# PARAMS: /v1/posts/<id>
# - <id> {string}: 문서의 아이디(_id)
# 본인이 작성한 글 수정
PUT http://localhost:5001/v1/posts/602dd907c9feb347bc5c3aa0
Content-Type: application/json
x-access-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDJkYmM5NmRmMmVmMTQ2ODQzMmNiYjciLCJyb2xlIjoibWVtYmVyIiwiaW5mbyI6IjYwMmRiYzk3ZGYyZWYxNDY4NDMyY2JiOCIsImlhdCI6MTYxMzYxNzg5NiwiZXhwIjoxNjEzNjE4NDk2LCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAiLCJpc3MiOiJZT1VSIFNFUlZJQ0UgTkFNRSIsInN1YiI6ImFobm1vNzc3QGdtYWlsLmNvbSJ9.O8gAOiBcP_p7fyYLoYeBHoxy_kkN7p6DgC7wmOj5vOwvrd3PTJjxvxLjtZStwNM2bnnWsJHFWoHzZSXVSaQtOg

{
  "content": "본인이 작성한 글은 수정이 가능합니다."
}

###
# 로그인 하지 않은 사용자가 글 삭제
DELETE http://localhost:5001/v1/posts/602dd907c9feb347bc5c3aa0


###
# 다른 사용자가 글 삭제
DELETE http://localhost:5001/v1/posts/602dd907c9feb347bc5c3aa0
x-access-token: <다른 사용자의 access token 입력>

###
# 다른 사용자가 글 삭제
DELETE http://localhost:5001/v1/posts/602dd907c9feb347bc5c3aa0
x-access-token: <본인의 access token 입력>

###
# 삭제 확인
GET http://localhost:5001/v1/posts?limit=10&page=1